### ISSUE TITLE
Thanks for this wonderful tool!

### ISSUE THREAD

**Issue by jinfagang** [Slava/label-tool#4]
What is the shortcut of next image?

**Comment by jinfagang** [comment]
I got some errror when try to export data:

```
TypeError: Cannot read property '5uhy1a09o' of undefined
    at project.form.formParts.forEach (/root/dl/LabelOne/server/src/exporter.js:19:40)
    at Array.forEach (<anonymous>)
    at imgs.map.img (/root/dl/LabelOne/server/src/exporter.js:18:30)
    at Array.map (<anonymous>)
    at Object.exports.exportProject.projectId [as exportProject] (/root/dl/LabelOne/server/src/exporter.js:11:6)
    at app.get (/root/dl/LabelOne/server/src/index.js:317:12)
    at Layer.handle [as handle_request] (/root/dl/LabelOne/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/root/dl/LabelOne/server/node_modules/express/lib/router/route.js:137:13)
    at exports.checkLoginMiddleware (/root/dl/LabelOne/server/src/auth.js:32:5)
    at Layer.handle [as handle_request] (/root/dl/LabelOne/server/node_modules/express/lib/router/layer.js:95:5)

```

**Comment by Slava** [comment]
Hi, the shortcut to the next image is either to [Submit] or to [Skip] (depending if you want to mark the image as done or not).

I am not sure about that error, you might need to debug it on your side by looking at the code.

**Comment by JoachimVeulemans** [comment]
@jinfagang A fix is on the way [here](https://github.com/Slava/label-tool/pull/7) or check out my fork [here](https://github.com/JoachimVeulemans/label-tool).

**Comment by Slava** [comment]
The fix has been merged
