### ISSUE TITLE
message	"unauthenticated" in exported JSON

### ISSUE THREAD

**Issue by gerkulesov** [Slava/label-tool#6]
After annotating dataset I am trying to export JSON.
But there is only one string `message "unauthenticated"` in it.
What is wrong?

**Comment by gerkulesov** [comment]
After repeating export I got browser error "File not found: http://localhost:5000/api/projects/3/export'

Error output in console:
```
TypeError: Cannot read property 'oocaxo10i' of undefined
    at project.form.formParts.forEach (/home/gerkulesovr/label-tool/server/src/exporter.js:19:40)
    at Array.forEach (<anonymous>)
    at imgs.map.img (/home/gerkulesovr/label-tool/server/src/exporter.js:18:30)
    at Array.map (<anonymous>)
    at Object.exports.exportProject.projectId [as exportProject] (/home/gerkulesovr/label-tool/server/src/exporter.js:11:6)
    at app.get (/home/gerkulesovr/label-tool/server/src/index.js:317:12)
    at Layer.handle [as handle_request] (/home/gerkulesovr/label-tool/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gerkulesovr/label-tool/server/node_modules/express/lib/router/route.js:137:13)
    at exports.checkLoginMiddleware (/home/gerkulesovr/label-tool/server/src/auth.js:32:5)
    at Layer.handle [as handle_request] (/home/gerkulesovr/label-tool/server/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by JoachimVeulemans** [comment]
@gerkulesov A fix is on the way [here](https://github.com/Slava/label-tool/pull/7) or check out my fork [here](https://github.com/JoachimVeulemans/label-tool).

**Comment by Slava** [comment]
The fix has been merged.
